---
docker_install_conflicting_packages:
  - docker.io
  - docker-compose
  - docker-doc
  - docker-buildx
  - podman-docker
  - containerd
  - runc

docker_install_prerequisites:
  - ca-certificates
  - curl
  - python3-debian

docker_install_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

docker_install_keyring_path: /etc/apt/keyrings/docker.asc
docker_install_gpg_url: https://download.docker.com/linux/debian/gpg
docker_install_repo_uri: https://download.docker.com/linux/debian
docker_install_repo_component: stable

docker_install_log_max_size: 10m
docker_install_log_max_file: "3"

docker_install_users: []
