---
- name: Install Visual Studio Code based on OS
  ansible.builtin.include_tasks: "{{ lookup('ansible.builtin.first_found', install_vscode_task_files) }}"
  vars:
    install_vscode_task_files:
      - "{{ ansible_facts['distribution'] }}.yaml"
      - "{{ ansible_facts['os_family'] }}.yaml"
