---
install_spotify_prerequisites:
  - ca-certificates
  - curl

install_spotify_packages:
  - spotify-client

install_spotify_keyring_path: /etc/apt/trusted.gpg.d/spotify.asc
install_spotify_keyring_url: https://download.spotify.com/debian/pubkey_5384CE82BA52C83A.asc
install_spotify_repo_uri: https://repository.spotify.com
install_spotify_repo_suite: stable
install_spotify_repo_component: non-free
install_spotify_repo_architectures:
  - amd64 # 64-bit Intel/AMD (x86_64)
